# Site settings
title: Kevin Pelgrims
email: kevin.pelgrims@gmail.com
description: >
  Experiments with Android, Git, Gradle, the web, .NET and PowerShell.
url: "http://kevinpelgrims.com"
twitter_username: kevinpelgrims
github_username:  kevinpelgrims

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Outputting
permalink: /blog/:year/:month/:day/:title/
