# Site settings
title: Kevin Pelgrims
email: kevin.pelgrims@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random experiments with Android, Git, Gradle, the web, .NET and PowerShell.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://kevinpelgrims.com" # the base hostname & protocol for your site
twitter_username: kevinpelgrims
github_username:  kevinpelgrims

# Build settings
markdown: kramdown

# Outputting
permalink: /:year/:month/:day/:title